# Site settings
title: Solace Samples JavaRTO
summary: These tutorials get you up to speed sending and receiving messages with Solace technology.
baseurl: "/solace-samples-javarto"
repository: https://github.com/SolaceSamples/solace-samples-javarto

# Also see _includes/intro.html to customize the description which gets included in index.html.

# Links
links-downloads: //solace.com/downloads/
links-community: //solace.com/support/
links-get-started: //dev.solace.com/get-started/dotnet-tutorials/
links-solaceCloud-setup: //solace.com/cloud/
docs-javarto-api: //docs.solace.com/API-Developer-Online-Ref-Documentation/jrto/index.html
